# Model arguments
model_name_or_path: /mnt/public/share/models/DeepSeek-R1-Distill-Qwen-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: /mnt/public/yhz/open-rs-main/open-rs-full_with_cache-qwen7b
system_prompt: "A conversation between User and Assistant. The user asks a question, and the Assistant solves it. The assistant first thinks about the reasoning process in the mind and then provides the user with the answer, and put your final answer within \\boxed{{}} . The reasoning process and answer are enclosed within <think> </think> and <answer> </answer> tags, respectively, i.e., <think> reasoning process here </think> <answer> answer here </answer>. Note that respond by English, NOT use other languages."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_enforce_eager: true
vllm_gpu_memory_utilization: 0.5
do_eval: false
gradient_accumulation_steps: 3
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: OpenRS-GRPO
hub_strategy: every_save
learning_rate: 1.0e-06
log_completions: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 512
max_completion_length: 2048
num_generations: 6
num_train_epochs: 4
output_dir: data/OpenRS-GRPO-Cache-test-7b-Cache
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- wandb
reward_funcs:
- format
- cosine
- accuracy
reward_weights:
- 1.0
- 1.0
- 1.0
save_strategy: "steps"
save_steps: 200
seed: 42
temperature: 0.7
warmup_ratio: 0.1
dataloader_drop_last: true